# Generated by Django 4.2.2 on 2023-06-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artistas', '0001_initial'),
        ('Canciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artistas.artista')),
                ('song_list', models.ManyToManyField(to='Canciones.song')),
            ],
        ),
    ]
